### ISSUE TITLE
SVN not enabled by default?

### ISSUE THREAD

**Issue by fniessen** [robobenklein/p10k#3]
Hello -- and many thanks for this super fast prompt!

It's a must for me, as I do want Git and SVN status on my prompt, and fast.

Though, I did not do anything, just cloned and then sourcing zinc.zsh, I don't see any SVN info in my prompt.  Do I have to do something special?

PS- I see I do have ~/.dotfiles/plugins/oh-my-zsh/plugins/svn on my disk. Is that a trouble?
PPS- Using this with Oh My Zsh! from Cygwin on Windows...

Best regards,
Fabrice

**Comment by robobenklein** [comment]
You can test to make sure there's not something else interfering by using `vcs_info` manually:

```
autoload -Uz vcs_info
vcs_info
echo $vcs_info_msg_0_
```

That should display the status of any git/svn repo unless there's a different problem.

If your working dir isn't in a repo though it won't output anything.

If you see it in git repos but not svn, check which backends are enabled:

```
vcs_info
echo $VCS_INFO_backends
```

**Comment by fniessen** [comment]
I do not understand; everything seems enabled:

> echo $vcs_info_msg_0_
(svn)-[2019-0403%20-%20Locate%20Equipment:348]-

> echo $VCS_INFO_backends
bzr cdv cvs darcs fossil git hg mtn p4 svk svn tla

and I even see the "Loading" gray part of the prompt, which disappears and does not output anything, at the end, as if I wasn't in a SVN dir?

I've a small video showing this.  How can I share it with you?

**Comment by robobenklein** [comment]
Found the problem, making the fix right now...

**Comment by robobenklein** [comment]
Fix committed on master, let me know if it works!

**Comment by fniessen** [comment]
It does work; only diff is that the branch name contains spaces (NOT my choice!) and these aren't rendered in the prompt, which I do consider as not fully reliable, somehow.  Any objection for letting them be displayed?

**Comment by robobenklein** [comment]
I don't have access to many SVN repos, could you show a pic of that?

**Comment by fniessen** [comment]
For sure.  Any suggestion where to share it?

**Comment by robobenklein** [comment]
You should be able to paste images directly in a github comment. If it's in the clipboard just Ctrl-V, otherwise drag the image into the comment box.

**Comment by fniessen** [comment]
Oh, here's one anyway: https://www.screencast.com/t/SVv3RE9Sm (but I'd like to know your suggested way to exchange such stuff).

**Comment by robobenklein** [comment]
![image](https://user-images.githubusercontent.com/5423266/60301457-721b8780-98ff-11e9-96aa-e4f52d9a6baa.png)
( ^ I just hit copy image and then pasted it here)

Yeah, those `%20` things are html codes, so I think the temporary 'solution' would be to do a regex on it that does the `%20` -> ` ` replacement.

It seems to be from some strange config in ZSH's vcs_info script, so it might be awhile before I determine the proper way to fix it.

P.S. Also if you want to shorten those huge paths I'd recommend looking at the different cwd shortening options:
`zinc_opts[zincs_cwd]=';;;;rtab;-t;-l'` ( docs in https://github.com/robobenklein/zinc/blob/master/zsdoc/zincs_cwd.adoc )

**Comment by fniessen** [comment]
Thanks!

Just pasted your above option line for shortening the prompt… but now I've this:

![image](https://user-images.githubusercontent.com/1748469/60324505-3fb46d80-9985-11e9-8735-78171fb7d444.png)

**Comment by robobenklein** [comment]
Wow! That's not something I've seen before....

I don't have access to any Windows machines so I'm not quite sure where that's coming from...

The raw function can be run by itself with `_zincs_cwd_strat_rtab -f && echo $REPLY`, I based it off a fairly old snippet for traversing the directory tree, so it might be unsupported on that platform?

Does the same happen in a clean session? Do you perhaps have `cd` as an alias or a function to something else?

**Comment by robobenklein** [comment]
Actually, I think the SVN enabled issue is fixed, and I'm 90% certain I fixed the rtab spam issue in https://github.com/robobenklein/zinc/commit/fc543df45b47742116e4693f4ad3d6c56df6250f so I'll close this one for now.

Feel free to reopen if the svn thing is still a problem.

**Comment by fniessen** [comment]
Dear Ben, I'm up to date, but I don't see any space for the %20 character: everything is "glued" together. Is this normal?

![image](https://user-images.githubusercontent.com/1748469/60332630-8d39d600-9997-11e9-83ec-51be3e058efa.png)

**Comment by robobenklein** [comment]
This is "normal" but not desired...

Will work on this in #9

**Comment by fniessen** [comment]
About the shortening of the path, here's the results:

_zincs_cwd_strat_rtab -f && echo $REPLY
/c/d/D/T/C/w/application

for example. So, that does work fine.

But I don't think I'm interested in that anyway: it becomes too cryptic. I should see at least a couple of parts, but it's difficult to be able to determine if it's the first dir + the two last, for example. I don't think there is a golden rule.
