### ISSUE TITLE
Space absent between branch name and status icon

### ISSUE THREAD

**Issue by fniessen** [robobenklein/p10k#5]
Detail, though annoying: in your video, I see "dev o" (space between the branch name and some status icon). In my case, there is no space (for my projects) between "master" and the "o" icon. Any idea why?

**Comment by robobenklein** [comment]
Ah, this is a difference between using `gitstatus` or not. ( https://github.com/romkatv/gitstatus )

I can add that space back into the non-gitstatus vcs if you want.

**Comment by fniessen** [comment]
I will try the above.

Yes, I'd consider that it should behave "correctly" (with a space) in both situations.  So, I'd vote for adding the space in there in the non-gitstatus vcs as well.

**Comment by robobenklein** [comment]
Already did so! Whoops! I agreed that the space was better.
